// softlvds_rx.v

// Generated using ACDS version 25.1 1129

`timescale 1 ps / 1 ps
module softlvds_rx (
		input  wire       rx_inclock,    //    rx_inclock.rx_inclock
		input  wire [0:0] rx_in,         //         rx_in.rx_in
		output wire [9:0] rx_out,        //        rx_out.rx_out
		input  wire       rx_data_reset, // rx_data_reset.rx_data_reset
		input  wire       rx_data_align  // rx_data_align.rx_data_align
	);

	altera_soft_lvds_rx_uP1RPNs2 softlvds_rx_inst (
		.rx_inclock            (rx_inclock),    //    rx_inclock.rx_inclock
		.rx_in                 (rx_in),         //         rx_in.rx_in
		.rx_out                (rx_out),        //        rx_out.rx_out
		.rx_data_reset         (rx_data_reset), // rx_data_reset.rx_data_reset
		.rx_data_align         (rx_data_align), // rx_data_align.rx_data_align
		.rx_locked             (),              //   (terminated)
		.rx_channel_data_align (1'b0),          //   (terminated)
		.rx_cda_reset          (1'b0),          //   (terminated)
		.rx_data_align_reset   (1'b0)           //   (terminated)
	);

endmodule
