// softlvds_tx.v

// Generated using ACDS version 25.1 1129

`timescale 1 ps / 1 ps
module softlvds_tx (
		input  wire       tx_inclock,    //    tx_inclock.tx_inclock
		input  wire       tx_syncclock,  //  tx_syncclock.tx_syncclock
		input  wire       tx_data_reset, // tx_data_reset.tx_data_reset
		input  wire [9:0] tx_in,         //         tx_in.tx_in
		output wire [0:0] tx_out         //        tx_out.tx_out
	);

	altera_soft_lvds_tx_uS1HUqyJ softlvds_tx_inst (
		.tx_inclock    (tx_inclock),    //    tx_inclock.tx_inclock
		.tx_syncclock  (tx_syncclock),  //  tx_syncclock.tx_syncclock
		.tx_data_reset (tx_data_reset), // tx_data_reset.tx_data_reset
		.tx_in         (tx_in),         //         tx_in.tx_in
		.tx_out        (tx_out),        //        tx_out.tx_out
		.tx_outclock   (),              //   (terminated)
		.tx_coreclock  (),              //   (terminated)
		.tx_locked     ()               //   (terminated)
	);

endmodule
