# For GIT
set git_sha [exec git rev-parse --short HEAD]
puts "GIT SHA: $git_sha"
if { [exec git status --porcelain --u=no] == "" } {
    set repo_state 0
} else {
    set repo_state 1
}
if { $repo_state == 0 } {
    set string_state "clean"
} else {
    set string_state "dirty"
}
puts "Repository state: $string_state"

# Create a version file
set version_path ../inc/
set version_filename version_pkg

set version_file $version_path$version_filename
append template_file $version_file .sv

set generated_file $version_path
append generated_file auto_$version_filename
append generated_file .sv

# Read from version.sv to create version_gen.sv
set fpRead [open $template_file r]
set fpWrite [open $generated_file w]

set hashString BADC0DE
set stateString "DEFAULT_VERSION_STATE ="

puts $fpWrite "// *** THIS IS A GENERATED FILE ***"
puts $fpWrite "// DO NOT EDIT THIS FILE MANUALLY"

while {[gets $fpRead line] >= 0} {
    set line [string trimright $line]
    if {[string match *$hashString* $line]} {
        regsub -all $hashString $line $git_sha line
    }
    if {[string match *$stateString* $line]} {
        if {$repo_state == 0} {
            # Replace default dirty state with clean state
            regsub f $line 0 line
        }
    }
    puts $fpWrite $line
}

close $fpRead
close $fpWrite

puts "Wrote GIT info to $generated_file"
